"""Reading and writing the stream overlays' settings.

The overlays are plain files in `stream/`, and they stay editable by hand
-- this module is the launcher's way in, not a new source of truth. Two
things live here:

* **Geometry.** The framed layouts declare their openings as CSS custom
  properties in the first twenty lines (`--box-x`, `--cam-w`, ...). This
  reads those numbers and writes them back in place, touching nothing
  else in the file. The guide label is generated by the page from the
  same properties, so a moved box cannot leave a stale caption behind.

* **Switches.** The camera opening and the alignment guide are written to
  `stream/config.js` as one `CONFIG({...})` call. A `.js` file rather
  than JSON for the same reason as the rest of the folder: OBS loads
  these pages over `file://`, where `fetch()` is blocked but loading a
  script from the same folder is allowed.

No PySide6 here, so the whole thing is testable without a display.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

GB_W, GB_H = 160, 144


@dataclass(frozen=True)
class Layout:
    """One overlay file, and what it can be asked about."""

    filename: str
    title: str
    canvas: tuple[int, int]
    framed: bool

    @property
    def width(self) -> int:
        return self.canvas[0]

    @property
    def height(self) -> int:
        return self.canvas[1]


LAYOUTS = (
    Layout("overlay-framed.html", "Framed — landscape", (1920, 1080), True),
    Layout("overlay-framed-vertical.html", "Framed — vertical", (1080, 1920), True),
    Layout("overlay.html", "Floating — landscape", (1920, 1080), False),
    Layout("overlay-vertical.html", "Floating — vertical", (1080, 1920), False),
)


class StreamConfigError(Exception):
    """A file was missing, unreadable, or not shaped the way we expect."""


@dataclass
class Rect:
    x: int
    y: int
    w: int
    h: int

    def as_tuple(self) -> tuple[int, int, int, int]:
        return (self.x, self.y, self.w, self.h)

    @property
    def scale(self) -> float | None:
        """Whole multiple of the Game Boy screen, if it is one."""
        if self.w % GB_W or self.h % GB_H:
            return None
        n = self.w // GB_W
        return float(n) if n == self.h // GB_H else None

    def describe(self) -> str:
        text = f"position {self.x}, {self.y} · size {self.w} × {self.h}"
        n = self.scale
        if n:
            return f"{text} ({n:g}× of {GB_W}×{GB_H})"
        return text


def _prop(text: str, name: str) -> int | None:
    m = re.search(rf"--{re.escape(name)}\s*:\s*(-?\d+)px\s*;", text)
    return int(m.group(1)) if m else None


def read_rects(path: Path) -> dict[str, Rect]:
    """Return the {'box': Rect, 'cam': Rect} an overlay declares.

    A layout with no such properties -- the two floating ones -- gives an
    empty dict rather than an error, since having none is normal.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise StreamConfigError(f"cannot read {path.name}: {exc}") from exc

    out: dict[str, Rect] = {}
    for prefix in ("box", "cam"):
        vals = [_prop(text, f"{prefix}-{axis}") for axis in "xywh"]
        if all(v is not None for v in vals):
            out[prefix] = Rect(*vals)  # type: ignore[arg-type]
    return out


def validate(rect: Rect, canvas: tuple[int, int], what: str) -> str | None:
    """Return a complaint about this rectangle, or None if it is fine."""
    cw, ch = canvas
    if rect.w < GB_W or rect.h < GB_H:
        return f"The {what} is smaller than the Game Boy screen ({GB_W}×{GB_H})."
    if rect.x < 0 or rect.y < 0:
        return f"The {what} starts off the left or top of the canvas."
    if rect.x + rect.w > cw or rect.y + rect.h > ch:
        return (
            f"The {what} runs off the canvas: it ends at "
            f"{rect.x + rect.w}, {rect.y + rect.h} and the canvas is {cw}×{ch}."
        )
    return None


def write_rects(path: Path, rects: dict[str, Rect]) -> None:
    """Write the numbers back, in place, changing nothing else.

    Each property is replaced where it already stands, so the comments
    that explain them -- and any hand edit elsewhere in the file -- come
    through untouched. A property the file does not declare is an error
    rather than something to append: it means this is not the file we
    think it is.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise StreamConfigError(f"cannot read {path.name}: {exc}") from exc

    for prefix, rect in rects.items():
        for axis, value in zip("xywh", rect.as_tuple()):
            name = f"{prefix}-{axis}"
            pattern = rf"(--{re.escape(name)}\s*:\s*)-?\d+px\s*;"
            text, n = re.subn(pattern, rf"\g<1>{value}px;", text, count=1)
            if not n:
                raise StreamConfigError(
                    f"{path.name} does not declare --{name}; leaving it alone"
                )

    _write_atomic(path, text)


SWITCHES = ("cam", "guide", "timer", "splits", "tracker", "inputs")

CONFIG_HEADER = """\
/* Stream overlay switches.
 *
 * Written by the launcher's Stream page, and safe to edit by hand. The
 * overlays load this the same way they load now.js: as a script from
 * their own folder, because OBS opens them over file:// where fetch()
 * is blocked.
 *
 *   cam      a second, camera-shaped opening in the framed layouts
 *   guide    print each opening's exact rectangle over it, for lining a
 *            capture up in OBS -- turn it off before going live
 *   timer    the file clock, to hundredths
 *   splits   the route, with the segment you are on marked
 *   tracker  the item grid
 *   inputs   the buttons being held
 *
 * Any of the last four also puts the rail in run mode, where the "now
 * building" line and the standing plaque step aside.
 */
"""


def read_switches(folder: Path) -> dict[str, bool]:
    """Current switch state. Missing or damaged file reads as all off."""
    out = {k: False for k in SWITCHES}
    try:
        text = (folder / "config.js").read_text(encoding="utf-8")
    except OSError:
        return out
    m = re.search(r"CONFIG\(\s*(\{.*?\})\s*\)\s*;", text, re.S)
    if not m:
        return out
    try:
        data = json.loads(re.sub(r"(\w+)\s*:", r'"\1":', m.group(1)))
    except ValueError:
        return out
    for key in out:
        out[key] = bool(data.get(key, False))
    return out


def write_switches(folder: Path, switches: dict[str, bool]) -> None:
    body = ", ".join(
        f"{k}: {'true' if switches.get(k) else 'false'}" for k in SWITCHES
    )
    _write_atomic(folder / "config.js", f"{CONFIG_HEADER}CONFIG({{{body}}});\n")


def read_now(folder: Path) -> str:
    """The current "now building" line, or '' if there is not one."""
    try:
        text = (folder / "now.js").read_text(encoding="utf-8")
    except OSError:
        return ""
    m = re.search(r"NOW\(\s*([\"'])(.*?)\1\s*\)\s*;", text, re.S)
    if not m:
        return ""
    return m.group(2).replace('\\"', '"').replace("\\\\", "\\")


def write_now(folder: Path, line: str) -> None:
    """Write the status line, escaped -- it is typed by a person."""
    safe = "".join(c for c in line if c >= " ").replace("\\", "\\\\").replace('"', '\\"')
    _write_atomic(
        folder / "now.js",
        "/* The line every overlay shows. Edit and save; they pick it up\n"
        " * within a few seconds, no need to touch OBS. */\n"
        f'NOW("{safe}");\n',
    )


def _write_atomic(path: Path, text: str) -> None:
    """Write beside the target and rename over it.

    OBS re-reads these files several times a second while the overlay is
    live. A half-written one is a syntax error on stream, so it never
    exists: the rename is what the browser sees.
    """
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
    except OSError as exc:
        raise StreamConfigError(f"cannot write {path.name}: {exc}") from exc


def snap(rect: Rect, canvas: tuple[int, int]) -> Rect:
    """Nearest whole multiple of the Game Boy screen that still fits.

    Flat mode is 160×144 pixels; at a whole multiple every source pixel
    lands on the same number of screen pixels and the art stays sharp.
    Between multiples it does not, which is what this is for.
    """
    cw, ch = canvas
    n = max(1, round(rect.w / GB_W))
    while n > 1 and (n * GB_W > cw - rect.x or n * GB_H > ch - rect.y):
        n -= 1
    return Rect(rect.x, rect.y, n * GB_W, n * GB_H)


def file_url(path: Path) -> str:
    """A file:// URL for OBS's browser source when Local file is off."""
    return path.resolve().as_uri()


# ---------------------------------------------------------------------------
# LiveSplit
# ---------------------------------------------------------------------------
# The player reads this, not the overlays: it says whether to push splits
# down a socket to LiveSplit and on which port. It lives beside the
# routes because anyone editing routes by hand is already in that folder.

LIVESPLIT_DEFAULT_PORT = 16834

LIVESPLIT_HEADER = """\
# Whether the player pushes splits to LiveSplit's Server component.
#
# Start it in LiveSplit with right-click -> Control -> Start TCP Server.
# Loopback only, and a failed connection is silent and retried, so
# leaving this on with LiveSplit closed costs nothing.
"""


def read_livesplit(folder: Path) -> tuple[bool, int]:
    """(enabled, port). A missing file is off, which suits most people."""
    on, port = False, LIVESPLIT_DEFAULT_PORT
    try:
        text = (folder / "livesplit.txt").read_text(encoding="utf-8")
    except OSError:
        return on, port
    for line in text.splitlines():
        m = re.match(r"\s*(\w+)\s*=\s*(\d+)", line)
        if not m:
            continue
        if m.group(1) == "enabled":
            on = m.group(2) != "0"
        elif m.group(1) == "port":
            port = int(m.group(2))
    if not (0 < port < 65536):
        port = LIVESPLIT_DEFAULT_PORT
    return on, port


def write_livesplit(folder: Path, enabled: bool, port: int) -> None:
    if not (0 < port < 65536):
        port = LIVESPLIT_DEFAULT_PORT
    _write_atomic(
        folder / "livesplit.txt",
        f"{LIVESPLIT_HEADER}enabled = {1 if enabled else 0}\nport = {port}\n",
    )
