#!/usr/bin/env python3
"""Checks the launcher's read/write of the stream overlay settings.

These functions edit files a stream is reading live, so the failure mode
is a syntax error on someone's canvas mid-broadcast. Everything here runs
against copies of the real overlays in a temp folder -- never the repo's
own -- so a bug in the writer cannot damage the originals while proving
itself.

  python3 tools/stream_config_test.py
"""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "launcher"))

import stream_config as sc  # noqa: E402

failures = 0


def check(name: str, got, want) -> None:
    global failures
    if got == want:
        print(f"ok   {name}")
    else:
        print(f"FAIL {name}\n       got  {got!r}\n       want {want!r}")
        failures += 1


def truthy(name: str, cond) -> None:
    check(name, bool(cond), True)


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        folder = Path(tmp) / "stream"
        shutil.copytree(ROOT / "stream", folder)

        # -- geometry, as the overlays ship it ------------------------
        framed = folder / "overlay-framed.html"
        rects = sc.read_rects(framed)
        check("landscape box is read", rects["box"].as_tuple(), (52, 36, 1120, 1008))
        truthy("landscape box is a whole multiple", rects["box"].scale == 7.0)
        truthy("landscape camera is read", "cam" in rects)

        vert = sc.read_rects(folder / "overlay-framed-vertical.html")
        check("vertical box is read", vert["box"].as_tuple(), (85, 236, 800, 720))
        truthy("vertical box is a whole multiple", vert["box"].scale == 5.0)

        # A floating layout declares no openings, and that is not an error.
        check("a floating layout has no rectangles",
              sc.read_rects(folder / "overlay.html"), {})

        # -- writing back ---------------------------------------------
        before = framed.read_text(encoding="utf-8")
        moved = sc.Rect(100, 60, 960, 864)
        sc.write_rects(framed, {"box": moved})
        after = framed.read_text(encoding="utf-8")
        check("the new numbers are read back",
              sc.read_rects(framed)["box"].as_tuple(), moved.as_tuple())
        check("the camera is left alone",
              sc.read_rects(framed)["cam"].as_tuple(), rects["cam"].as_tuple())
        check("only the four numbers changed",
              len(before.splitlines()), len(after.splitlines()))
        truthy("the explaining comments survive", "160 x 7" in after)
        truthy("the page still loads its stylesheet", "epoch-live.css" in after)

        # The guide caption is generated by the page from these same
        # properties, so a moved box must not leave a number behind.
        truthy("no stale rectangle is baked into the file",
               "1120 × 1008" not in after and "52, 36" not in after)

        # A file that does not declare a property is refused, not appended to.
        plain = folder / "overlay.html"
        try:
            sc.write_rects(plain, {"box": moved})
            check("writing to a layout with no openings is refused", "wrote", "refused")
        except sc.StreamConfigError:
            check("writing to a layout with no openings is refused",
                  "refused", "refused")

        # -- validation -----------------------------------------------
        canvas = (1920, 1080)
        check("a rectangle that fits is accepted",
              sc.validate(sc.Rect(52, 36, 1120, 1008), canvas, "opening"), None)
        truthy("a rectangle running off the canvas is caught",
               sc.validate(sc.Rect(1000, 36, 1120, 1008), canvas, "opening"))
        truthy("a negative origin is caught",
               sc.validate(sc.Rect(-4, 36, 1120, 1008), canvas, "opening"))
        truthy("a rectangle below one screen is caught",
               sc.validate(sc.Rect(0, 0, 100, 90), canvas, "opening"))

        # -- snapping --------------------------------------------------
        check("an awkward size snaps to a whole multiple",
              sc.snap(sc.Rect(52, 36, 1100, 990), canvas).as_tuple(),
              (52, 36, 1120, 1008))
        snapped = sc.snap(sc.Rect(1200, 36, 900, 800), canvas)
        check("snapping never runs off the canvas",
              sc.validate(snapped, canvas, "opening"), None)

        # -- switches --------------------------------------------------
        check("missing config reads as all off",
              sc.read_switches(folder), {"cam": False, "guide": False})
        sc.write_switches(folder, {"cam": True, "guide": False})
        check("switches round trip",
              sc.read_switches(folder), {"cam": True, "guide": False})
        text = (folder / "config.js").read_text(encoding="utf-8")
        truthy("switches are written as one CONFIG call", "CONFIG({" in text)
        truthy("switches are real booleans, not strings", "cam: true" in text)

        (folder / "config.js").write_text("this is not javascript {", encoding="utf-8")
        check("a damaged config reads as all off rather than throwing",
              sc.read_switches(folder), {"cam": False, "guide": False})

        # -- the status line -------------------------------------------
        sc.write_now(folder, "chasing down the tree shapes")
        check("the status line round trips",
              sc.read_now(folder), "chasing down the tree shapes")
        # It is typed by a person, so it must not be able to end the string.
        sc.write_now(folder, 'the "best" \\ ring\nand a second line')
        raw = (folder / "now.js").read_text(encoding="utf-8")
        truthy("quotes in the status line are escaped", '\\"best\\"' in raw)
        truthy("backslashes are escaped", "\\\\ ring" in raw)
        truthy("the call stays on one line", raw.count("NOW(") == 1
               and "\n" not in raw.split("NOW(")[1].split(");")[0])
        check("it still reads back as typed, minus the newline",
              sc.read_now(folder), 'the "best" \\ ringand a second line')

        # -- no scraps left behind --------------------------------------
        leftovers = sorted(p.name for p in folder.glob("*.tmp"))
        check("no temporary files are left in the folder", leftovers, [])

    if failures:
        print(f"{failures} check(s) FAILED")
        return 1
    print("[stream_config_test] all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
