# Build-time cart generation.
#
# This project ships no recompiled game code. Instead, each cart's C is
# produced on your machine, from your own ROM, by the MIT-licensed `gbrecomp`
# recompiler -- the same model Zelda64Recomp and Ship of Harkinian use. The
# translated output never enters the repository and never leaves your disk.
#
# Generation runs at *configure* time rather than build time because CMake has
# to know the source list before it can define a target, and gbrecomp emits a
# variable number of files (~48 per cart). It's cached against the ROM, so a
# reconfigure is cheap unless the ROM changes.

include_guard(GLOBAL)

# Configure + build gbrecomp once, into the build tree. Sets EPOCH_GBRECOMP.
function(epoch_build_recompiler source_dir)
    set(tool_build "${CMAKE_BINARY_DIR}/_gbrecomp")
    set(tool_exe "${tool_build}/bin/gbrecomp${CMAKE_EXECUTABLE_SUFFIX}")

    if(NOT EXISTS "${tool_exe}")
        message(STATUS "Building the gbrecomp recompiler (one time)")
        execute_process(
            COMMAND ${CMAKE_COMMAND} -S "${source_dir}" -B "${tool_build}"
                    -DCMAKE_BUILD_TYPE=Release
            RESULT_VARIABLE rc OUTPUT_QUIET
        )
        if(NOT rc EQUAL 0)
            message(FATAL_ERROR "Could not configure the recompiler in ${source_dir}")
        endif()
        execute_process(
            COMMAND ${CMAKE_COMMAND} --build "${tool_build}" --target gbrecomp
                    --parallel ${EPOCH_JOBS}
            RESULT_VARIABLE rc
        )
        if(NOT rc EQUAL 0 OR NOT EXISTS "${tool_exe}")
            message(FATAL_ERROR "Failed to build gbrecomp")
        endif()
    endif()

    set(EPOCH_GBRECOMP "${tool_exe}" PARENT_SCOPE)
endfunction()

# Recompile one ROM. Sets <out_prefix>_SOURCES and <out_prefix>_DIR.
function(epoch_generate_cart rom_path id out_prefix)
    set(gen_dir "${CMAKE_BINARY_DIR}/generated/${id}")
    set(stamp "${gen_dir}/.stamp")

    # Regenerate when the ROM changes, or when the recompiler is newer than
    # the last run (a gbrecomp bump should reproduce the cart).
    set(needs_gen TRUE)
    if(EXISTS "${stamp}")
        file(READ "${stamp}" prev_hash)
        file(SHA256 "${rom_path}" rom_hash)
        if(prev_hash STREQUAL rom_hash AND "${stamp}" IS_NEWER_THAN "${EPOCH_GBRECOMP}")
            set(needs_gen FALSE)
        endif()
    endif()

    if(needs_gen)
        message(STATUS "Recompiling ${id} from ${rom_path} (about a minute)")
        file(REMOVE_RECURSE "${gen_dir}")

        # --prefix-symbols keeps two carts from colliding in one binary.
        # --emit-asset-loader + --bss-rom-data keep ROM bytes out of the
        # binary's data section; the loader fills them from the user's own
        # copy at first boot.
        set(args "${rom_path}" -o "${gen_dir}" -j ${EPOCH_JOBS}
                 --prefix-symbols --emit-asset-loader --bss-rom-data)

        # Optional symbol names, e.g. from Stewmath/oracles-disasm. Purely
        # cosmetic -- it makes generated functions readable in a debugger.
        get_filename_component(rom_dir "${rom_path}" DIRECTORY)
        if(EXISTS "${rom_dir}/${id}.sym")
            message(STATUS "  using symbols from ${rom_dir}/${id}.sym")
            list(APPEND args --symbols "${rom_dir}/${id}.sym")
        endif()

        execute_process(COMMAND "${EPOCH_GBRECOMP}" ${args}
                        RESULT_VARIABLE rc OUTPUT_QUIET)
        if(NOT rc EQUAL 0)
            message(FATAL_ERROR "gbrecomp failed on ${rom_path}")
        endif()

        # gbrecomp's generated *_main.c includes this header but doesn't emit
        # it, so we write it. One opaque section covering the whole ROM: the
        # mod layer patches rom.bin wholesale, so a finer split would buy
        # nothing today.
        string(TOUPPER "${id}" ID_UPPER)
        file(SIZE "${rom_path}" rom_size)
        file(WRITE "${gen_dir}/assets_manifest_${id}.h"
"/* Generated by cmake/GenerateCarts.cmake -- do not edit. */
#ifndef ${ID_UPPER}_ASSETS_MANIFEST_H
#define ${ID_UPPER}_ASSETS_MANIFEST_H

#include <stddef.h>
#include <stdint.h>

#ifndef PG1_ASSET_ENTRY_DEFINED
#define PG1_ASSET_ENTRY_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint32_t size;
    const char* path;
} Pg1AssetEntry;
#endif

#define ${ID_UPPER}_ASSETS_MANIFEST_COUNT 1

static const Pg1AssetEntry ${ID_UPPER}_ASSETS_MANIFEST[${ID_UPPER}_ASSETS_MANIFEST_COUNT] = {
    { 0x00000000, ${rom_size}u, \"rom.bin\" },
};

#endif
")

        file(SHA256 "${rom_path}" rom_hash)
        file(WRITE "${stamp}" "${rom_hash}")
    endif()

    file(GLOB sources CONFIGURE_DEPENDS "${gen_dir}/*.c")
    if(NOT sources)
        message(FATAL_ERROR "No sources generated for ${id} in ${gen_dir}")
    endif()

    set(${out_prefix}_SOURCES "${sources}" PARENT_SCOPE)
    set(${out_prefix}_DIR "${gen_dir}" PARENT_SCOPE)
endfunction()

# Write the game table the runner compiles against, describing exactly the
# carts that were actually generated. Nothing about the cart list is hardcoded
# in C -- drop a different ROM in roms/ and it appears here.
function(epoch_write_game_table ids titles rom_paths out_header)
    set(entries "")
    list(LENGTH ids count)
    math(EXPR last "${count} - 1")

    foreach(i RANGE ${last})
        list(GET ids ${i} id)
        list(GET titles ${i} title)
        list(GET rom_paths ${i} rom_path)

        file(SIZE "${rom_path}" rom_size)
        file(SHA1 "${rom_path}" sha1_hex)
        file(SHA256 "${rom_path}" sha256_hex)
        get_filename_component(rom_name "${rom_path}" NAME)

        # Hashes go out as hex strings, not braced byte arrays: a
        # `{0x88, 0x03, ...}` initialiser makes the preprocessor read each
        # byte as its own macro argument, and the X-macro stops expanding.
        string(APPEND entries
            "    EPOCH_GAME(${id}, \"${id}\", \"${title}\", \"roms/${rom_name}\", \\\n"
            "                 ${rom_size}u, \"${sha256_hex}\", \"${sha1_hex}\") \\\n")
    endforeach()

    file(WRITE "${out_header}"
"/* Generated by cmake/GenerateCarts.cmake -- do not edit.
 *
 * The cart table, built from whatever ROMs were found in roms/ at configure
 * time. Hashes are of your own dumps, so verification is self-consistent
 * with the code that was generated from them.
 *
 * Consumed as an X-macro: define EPOCH_GAME(sym, id, title, rom, size,
 * sha256_hex, sha1_hex) and expand EPOCH_GAME_LIST. Both hashes are
 * lowercase hex strings.
 */
#ifndef EPOCH_GAMES_H
#define EPOCH_GAMES_H

#define EPOCH_GAME_COUNT ${count}

#define EPOCH_GAME_LIST \\
${entries}

#endif
")
endfunction()
